namespace LiveLingo.Core.Engines;

public interface ITranslationEngine : IDisposable
{
    IReadOnlyList<LanguageInfo> SupportedLanguages { get; }

    Task<string> TranslateAsync(
        string text,
        string sourceLanguage,
        string targetLanguage,
        CancellationToken ct = default);

    /// <summary>
    /// Streams translation token deltas as they are generated by the model.
    /// Each yielded string is a raw text fragment; the complete translation is
    /// their concatenation.
    /// The last update may carry <c>IsReplacement = true</c> when the quality
    /// guard triggered a cloud escalation, indicating the caller should replace
    /// all previously displayed partial text with the yielded value.
    /// </summary>
    IAsyncEnumerable<TranslationDelta> TranslateStreamingAsync(
        string text,
        string sourceLanguage,
        string targetLanguage,
        CancellationToken ct = default);

    bool SupportsLanguagePair(string sourceLanguage, string targetLanguage);
}

/// <summary>A single streaming token or replacement payload.</summary>
public sealed record TranslationDelta(string Text, bool IsReplacement = false);
